name = "onedrive-github-linker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-10"
kv_namespaces = [
  { binding = "kv", id = "<TEST_ID>" }
]
[build]
command = "cargo install -q worker-build && worker-build --release"
